# Generated by Django 4.0.6 on 2022-07-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=30, verbose_name='isbn')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('sell_count', models.IntegerField(verbose_name='sell_count')),
            ],
        ),
    ]
